[package]
name = "lotus-explorer-bridge"
version.workspace = true
description = "Narrow injected Explorer taskbar suppression bridge for Lotus"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
minhook = "0.9"
windows.workspace = true

[lints]
workspace = true
