[package]
name = "lotus-ui"
version.workspace = true
description = "Shared native interaction and visual primitives for Lotus"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
euclid.workspace = true
thiserror.workspace = true

[lints]
workspace = true
