[package]
name = "lotus-windows"
version.workspace = true
description = "Safe native Windows capabilities for Lotus"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
atomic-write-file.workspace = true
lotus-core.workspace = true
lotus-dock.workspace = true
lotus-media.workspace = true
lotus-shell-bridge.workspace = true
lotus-switcher.workspace = true
lotus-ui.workspace = true
lotus-update.workspace = true
image.workspace = true
resvg.workspace = true
sha2.workspace = true
thiserror.workspace = true
tiny-skia.workspace = true
windows.workspace = true
windows-core.workspace = true
windows-numerics.workspace = true
windows-registry.workspace = true
windows-result.workspace = true

[lints]
workspace = true
