mod error;
mod platform;
mod resource_cache;
pub mod responsiveness;

pub mod activation;
pub mod application_identity;
pub mod clipboard;
pub mod clock;
pub mod color_picker;
pub mod custom_image;
pub mod desktop;
pub mod diagnostics;
pub mod dpi;
pub mod dwm_thumbnail;
pub mod exclusive_taskbar;
mod explorer_bridge;
mod font;
pub mod graphics;
pub mod image_picker;
pub mod input;
pub mod launch;
pub mod media;
pub(crate) mod messages;
pub mod native_icon;
pub mod network;
pub mod search_catalog;
mod shell_bridge;
pub mod single_instance;
pub mod startup;
pub mod switcher_icons;
pub mod taskbar_badges;
pub mod taskbar_state;
pub mod tray;
pub mod update;
pub mod window;
pub mod window_tracker;

pub use error::NativeError;
pub use platform::windows::native_window::WindowHandle;
pub use platform::windows::{appbar, backdrop, dialog, interaction};
