#![allow(
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "generated by windows-core's COM implementation macro"
)]

use lotus_core::notification::NotificationSource;
use windows::Win32::Foundation::{HWND, LPARAM, RPC_E_CHANGED_MODE, WPARAM};
use windows::Win32::System::Com::{
    CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED, CoCreateInstance, CoInitializeEx,
    CoUninitialize,
};
use windows::Win32::System::Threading::GetCurrentThreadId;
use windows::Win32::System::Variant::VARIANT;
use windows::Win32::UI::Accessibility::{
    CUIAutomation, IUIAutomation, IUIAutomationElement,
    IUIAutomationPropertyChangedEventHandler,
    IUIAutomationPropertyChangedEventHandler_Impl, TreeScope_Descendants,
    TreeScope_Subtree, UIA_AutomationIdPropertyId, UIA_HelpTextPropertyId, UIA_PROPERTY_ID,
};
use windows::Win32::UI::WindowsAndMessaging::{
    EnumWindows, FindWindowExW, FindWindowW, GetWindowThreadProcessId, PostThreadMessageW,
    WM_APP,
};
use windows::core::{BOOL, Error as WindowsError, PCWSTR, Ref, implement, w};

const BADGE_WAKE_MESSAGE: u32 = WM_APP + 0x4CB;
const TASKBAR_BUTTON_CLASS: &str = "Taskbar.TaskListButtonAutomationPeer";

pub struct TaskbarBadgeController {
    automation: IUIAutomation,
    root: IUIAutomationElement,
    handler: IUIAutomationPropertyChangedEventHandler,
    _apartment: ComApartment,
}

impl TaskbarBadgeController {
    pub fn start() -> Result<Self, WindowsError> {
        let apartment = ComApartment::enter()?;
        // SAFETY: CUIAutomation is an in-process COM class and COM is initialized above.
        let automation = unsafe {
            CoCreateInstance::<_, IUIAutomation>(
                &CUIAutomation,
                None,
                CLSCTX_INPROC_SERVER,
            )?
        };
        let taskbar = taskbar_window()?;
        let host = taskbar_content_host(taskbar)?;
        // SAFETY: `host` is a live taskbar child HWND discovered immediately above.
        let root = unsafe { automation.ElementFromHandle(host)? };
        let handler: IUIAutomationPropertyChangedEventHandler = BadgeChangeHandler {
            owner_thread: current_thread_id(),
        }
        .into();
        // SAFETY: The automation client, root, and handler are retained together until Drop.
        unsafe {
            automation.AddPropertyChangedEventHandlerNativeArray(
                &root,
                TreeScope_Subtree,
                None::<&windows::Win32::UI::Accessibility::IUIAutomationCacheRequest>,
                &handler,
                &[UIA_HelpTextPropertyId, UIA_AutomationIdPropertyId],
            )?;
        }
        Ok(Self {
            automation,
            root,
            handler,
            _apartment: apartment,
        })
    }

    pub fn snapshot(&self) -> Result<Vec<NotificationSource>, WindowsError> {
        // SAFETY: The automation object and its root remain valid for this controller lifetime.
        let condition = unsafe { self.automation.CreateTrueCondition()? };
        // SAFETY: The condition belongs to this automation client and the query is synchronous.
        let elements = unsafe { self.root.FindAll(TreeScope_Descendants, &condition)? };
        // SAFETY: The returned array remains alive for all indexed element reads below.
        let length = unsafe { elements.Length()? };
        let mut sources = Vec::new();
        for index in 0..length {
            // SAFETY: `index` is bounded by the array length returned immediately above.
            let element = unsafe { elements.GetElement(index)? };
            // SAFETY: UI Automation owns the returned BSTR and windows-rs copies it safely.
            if unsafe { element.CurrentClassName()? } != TASKBAR_BUTTON_CLASS {
                continue;
            }
            // SAFETY: UI Automation owns each returned BSTR and windows-rs copies it safely.
            let automation_id = unsafe { element.CurrentAutomationId()? }.to_string();
            // SAFETY: UI Automation owns each returned BSTR and windows-rs copies it safely.
            let help_text = unsafe { element.CurrentHelpText()? }.to_string();
            // SAFETY: UI Automation owns each returned BSTR and windows-rs copies it safely.
            let name = unsafe { element.CurrentName()? }.to_string();
            if !is_supported_application(&automation_id, &name) {
                continue;
            }
            let exact_count = discord_badge_count(&self.automation, &automation_id);
            let Some(count) =
                exact_count.or_else(|| badge_count(&automation_id, &help_text))
            else {
                continue;
            };
            sources.push(NotificationSource {
                display_name: taskbar_display_name(&name).to_owned(),
                app_user_model_id: automation_id
                    .strip_prefix("Appid: ")
                    .unwrap_or(&automation_id)
                    .to_owned(),
                package_family_name: String::new(),
                count,
                count_is_lower_bound: exact_count.is_none() && is_discord(&automation_id),
            });
        }
        Ok(sources)
    }
}

impl Drop for TaskbarBadgeController {
    fn drop(&mut self) {
        // SAFETY: This removes the exact root and handler registration created by `start`.
        let _ = unsafe {
            self.automation
                .RemovePropertyChangedEventHandler(&self.root, &self.handler)
        };
    }
}

#[implement(IUIAutomationPropertyChangedEventHandler)]
struct BadgeChangeHandler {
    owner_thread: u32,
}

impl IUIAutomationPropertyChangedEventHandler_Impl for BadgeChangeHandler_Impl {
    fn HandlePropertyChangedEvent(
        &self,
        _sender: Ref<'_, IUIAutomationElement>,
        property_id: UIA_PROPERTY_ID,
        _new_value: &VARIANT,
    ) -> windows::core::Result<()> {
        if property_id == UIA_HelpTextPropertyId
            || property_id == UIA_AutomationIdPropertyId
        {
            post_badge_wake(self.owner_thread);
        }
        Ok(())
    }
}

pub const fn is_taskbar_badge_wake(message: u32) -> bool {
    message == BADGE_WAKE_MESSAGE
}

fn badge_count(automation_id: &str, description: &str) -> Option<u32> {
    if description.eq_ignore_ascii_case("no notifications") || description.trim().is_empty()
    {
        return None;
    }
    let number = description
        .split(|character: char| !character.is_ascii_digit())
        .find(|part| !part.is_empty())
        .and_then(|part| part.parse::<u32>().ok());
    match number {
        Some(_) if is_discord(automation_id) => Some(10),
        Some(0) => None,
        Some(value) => Some(value),
        None => Some(1),
    }
}

fn discord_badge_count(automation: &IUIAutomation, automation_id: &str) -> Option<u32> {
    let executable_name = match automation_id {
        "Appid: com.squirrel.Discord.Discord" => "Discord.exe",
        "Appid: com.squirrel.DiscordCanary.DiscordCanary" => "DiscordCanary.exe",
        _ => return None,
    };
    discord_windows(executable_name)
        .into_iter()
        .find_map(|window| discord_window_badge_count(automation, window))
}

fn discord_window_badge_count(automation: &IUIAutomation, window: HWND) -> Option<u32> {
    // SAFETY: `window` is a live top-level HWND found synchronously above.
    let root = unsafe { automation.ElementFromHandle(window) }.ok()?;
    // SAFETY: The condition and returned elements belong to this automation client.
    let condition = unsafe { automation.CreateTrueCondition() }.ok()?;
    // SAFETY: The query is synchronous and all COM values remain alive while traversed.
    let elements = unsafe { root.FindAll(TreeScope_Descendants, &condition) }.ok()?;
    // SAFETY: The walker belongs to this automation client.
    let walker = unsafe { automation.RawViewWalker() }.ok()?;
    // SAFETY: The returned array stays alive for all bounded indexed reads below.
    let length = unsafe { elements.Length() }.ok()?;
    for index in 0..length {
        // SAFETY: `index` is bounded by the array length returned above.
        let Ok(element) = (unsafe { elements.GetElement(index) }) else {
            continue;
        };
        // SAFETY: UI Automation owns the returned BSTR and windows-rs copies it safely.
        let Ok(value) = (unsafe { element.CurrentName() }) else {
            continue;
        };
        let value = value.to_string();
        let Ok(count) = value.parse::<u32>() else {
            continue;
        };
        // SAFETY: `element` belongs to this tree and the parent query is read-only.
        let Ok(parent) = (unsafe { walker.GetParentElement(&element) }) else {
            continue;
        };
        // SAFETY: UI Automation owns the returned BSTR and windows-rs copies it safely.
        let Ok(parent_class) = (unsafe { parent.CurrentClassName() }) else {
            continue;
        };
        let parent_class = parent_class.to_string();
        if parent_class.starts_with("lowerBadge_") {
            return Some(count);
        }
    }
    None
}

fn is_discord(automation_id: &str) -> bool {
    automation_id.starts_with("Appid: com.squirrel.Discord")
}

fn is_supported_application(automation_id: &str, name: &str) -> bool {
    is_discord(automation_id)
        || automation_id.to_ascii_lowercase().contains("slack")
        || taskbar_display_name(name).eq_ignore_ascii_case("Slack")
}

fn discord_windows(executable_name: &str) -> Vec<HWND> {
    let mut state = WindowSearch {
        executable_name,
        results: Vec::new(),
    };
    // SAFETY: EnumWindows invokes the callback synchronously while `state` remains live.
    let _ = unsafe {
        EnumWindows(
            Some(find_window),
            LPARAM((&raw mut state).addr().cast_signed()),
        )
    };
    state.results
}

struct WindowSearch<'a> {
    executable_name: &'a str,
    results: Vec<HWND>,
}

unsafe extern "system" fn find_window(window: HWND, parameter: LPARAM) -> BOOL {
    // SAFETY: `parameter` points to the live WindowSearch supplied to synchronous EnumWindows.
    let state = unsafe { &mut *(parameter.0 as *mut WindowSearch<'_>) };
    let mut process_id = 0;
    // SAFETY: EnumWindows supplied a valid HWND and the process ID pointer is writable.
    unsafe { GetWindowThreadProcessId(window, Some(&raw mut process_id)) };
    let matches = crate::window_tracker::process_image_path(process_id)
        .and_then(|path| {
            path.file_name()
                .map(|name| name.to_string_lossy().into_owned())
        })
        .is_some_and(|name| name.eq_ignore_ascii_case(state.executable_name));
    if matches {
        state.results.push(window);
    }
    BOOL(1)
}

fn taskbar_display_name(name: &str) -> &str {
    name.rsplit_once(" - ")
        .filter(|(_, suffix)| {
            suffix.ends_with("running window") || suffix.ends_with("running windows")
        })
        .map_or(name, |(display_name, _)| display_name)
}

fn taskbar_window() -> Result<HWND, WindowsError> {
    // SAFETY: Both class and title pointers are static or null and valid for the call.
    unsafe { FindWindowW(w!("Shell_TrayWnd"), PCWSTR::null()) }
}

fn taskbar_content_host(taskbar: HWND) -> Result<HWND, WindowsError> {
    // SAFETY: `taskbar` is live and both child and title pointers are valid for the call.
    unsafe {
        FindWindowExW(
            Some(taskbar),
            None,
            w!("Windows.UI.Composition.DesktopWindowContentBridge"),
            PCWSTR::null(),
        )
    }
}

fn current_thread_id() -> u32 {
    // SAFETY: GetCurrentThreadId has no preconditions.
    unsafe { GetCurrentThreadId() }
}

fn post_badge_wake(owner_thread: u32) {
    // SAFETY: The UI thread remains alive for the controller lifetime and receives value data only.
    let _ = unsafe {
        PostThreadMessageW(owner_thread, BADGE_WAKE_MESSAGE, WPARAM(0), LPARAM(0))
    };
}

struct ComApartment {
    uninitialize: bool,
}

impl ComApartment {
    fn enter() -> Result<Self, WindowsError> {
        // SAFETY: The reserved pointer is null and a successful call is balanced in Drop.
        let result = unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) };
        if result.is_ok() {
            Ok(Self { uninitialize: true })
        } else if result == RPC_E_CHANGED_MODE {
            Ok(Self {
                uninitialize: false,
            })
        } else {
            Err(result.into())
        }
    }
}

impl Drop for ComApartment {
    fn drop(&mut self) {
        if self.uninitialize {
            // SAFETY: Balances this guard's successful CoInitializeEx on the same thread.
            unsafe { CoUninitialize() };
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{badge_count, is_supported_application, taskbar_display_name};

    #[test]
    fn taskbar_badge_contract_handles_supported_apps() {
        assert_eq!(
            badge_count("Appid: com.squirrel.Discord.Discord", "9 notifications"),
            Some(10)
        );
        assert_eq!(
            badge_count("Appid: com.squirrel.slack.slack", "50 notifications"),
            Some(50)
        );
        assert!(is_supported_application(
            "Appid: com.squirrel.Discord.Discord",
            "Discord"
        ));
        assert!(is_supported_application(
            "Appid: com.squirrel.slack.slack",
            "Slack"
        ));
        assert!(!is_supported_application("Appid: com.example.Mail", "Mail"));
        assert_eq!(
            taskbar_display_name("Discord - 1 running window"),
            "Discord"
        );
    }
}
