[package]
name = "lotus-search"
version.workspace = true
description = "Application search feature for Lotus"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lotus-core.workspace = true
lotus-ui.workspace = true
fasteval.workspace = true

[lints]
workspace = true
