#![allow(
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "generated by windows-core's COM implementation macro"
)]

use lotus_core::notification::NotificationSource;
use windows::Win32::Foundation::{LPARAM, RPC_E_CHANGED_MODE, WPARAM};
use windows::Win32::System::Com::{
    CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED, CoCreateInstance, CoInitializeEx,
    CoUninitialize,
};
use windows::Win32::System::Threading::GetCurrentThreadId;
use windows::Win32::System::Variant::VARIANT;
use windows::Win32::UI::Accessibility::{
    CUIAutomation, IUIAutomation, IUIAutomationElement,
    IUIAutomationPropertyChangedEventHandler,
    IUIAutomationPropertyChangedEventHandler_Impl, TreeScope_Descendants,
    TreeScope_Subtree, UIA_AutomationIdPropertyId, UIA_HelpTextPropertyId, UIA_PROPERTY_ID,
};
use windows::Win32::UI::WindowsAndMessaging::{PostThreadMessageW, WM_APP};
use windows::core::{Error as WindowsError, Ref, implement};

use super::{discovery, providers};

const BADGE_WAKE_MESSAGE: u32 = WM_APP + 0x4CB;
const TASKBAR_BUTTON_CLASS: &str = "Taskbar.TaskListButtonAutomationPeer";

pub struct TaskbarBadgeController {
    automation: IUIAutomation,
    root: IUIAutomationElement,
    handler: IUIAutomationPropertyChangedEventHandler,
    _apartment: ComApartment,
}

impl TaskbarBadgeController {
    pub fn start() -> Result<Self, WindowsError> {
        let apartment = ComApartment::enter()?;
        // SAFETY: CUIAutomation is an in-process COM class and COM is initialized above.
        let automation = unsafe {
            CoCreateInstance::<_, IUIAutomation>(
                &CUIAutomation,
                None,
                CLSCTX_INPROC_SERVER,
            )?
        };
        let taskbar = discovery::taskbar_window()?;
        let host = discovery::taskbar_content_host(taskbar)?;
        // SAFETY: `host` is a live taskbar child HWND discovered immediately above.
        let root = unsafe { automation.ElementFromHandle(host)? };
        let handler: IUIAutomationPropertyChangedEventHandler = BadgeChangeHandler {
            owner_thread: current_thread_id(),
        }
        .into();
        // SAFETY: The automation client, root, and handler are retained together until Drop.
        unsafe {
            automation.AddPropertyChangedEventHandlerNativeArray(
                &root,
                TreeScope_Subtree,
                None::<&windows::Win32::UI::Accessibility::IUIAutomationCacheRequest>,
                &handler,
                &[UIA_HelpTextPropertyId, UIA_AutomationIdPropertyId],
            )?;
        }
        Ok(Self {
            automation,
            root,
            handler,
            _apartment: apartment,
        })
    }

    pub fn snapshot(&self) -> Result<Vec<NotificationSource>, WindowsError> {
        // SAFETY: The automation object and its root remain valid for this controller lifetime.
        let condition = unsafe { self.automation.CreateTrueCondition()? };
        // SAFETY: The condition belongs to this automation client and the query is synchronous.
        let elements = unsafe { self.root.FindAll(TreeScope_Descendants, &condition)? };
        // SAFETY: The returned array remains alive for all indexed element reads below.
        let length = unsafe { elements.Length()? };
        let mut sources = Vec::new();
        for index in 0..length {
            // SAFETY: `index` is bounded by the array length returned immediately above.
            let element = unsafe { elements.GetElement(index)? };
            // SAFETY: UI Automation owns the returned BSTR and windows-rs copies it safely.
            if unsafe { element.CurrentClassName()? } != TASKBAR_BUTTON_CLASS {
                continue;
            }
            // SAFETY: UI Automation owns each returned BSTR and windows-rs copies it safely.
            let automation_id = unsafe { element.CurrentAutomationId()? }.to_string();
            // SAFETY: UI Automation owns each returned BSTR and windows-rs copies it safely.
            let help_text = unsafe { element.CurrentHelpText()? }.to_string();
            // SAFETY: UI Automation owns each returned BSTR and windows-rs copies it safely.
            let name = unsafe { element.CurrentName()? }.to_string();
            if !providers::is_supported_application(&automation_id, &name) {
                continue;
            }
            let exact_count =
                providers::discord_badge_count(&self.automation, &automation_id);
            let Some(count) =
                exact_count.or_else(|| providers::badge_count(&automation_id, &help_text))
            else {
                continue;
            };
            sources.push(NotificationSource {
                display_name: providers::taskbar_display_name(&name).to_owned(),
                app_user_model_id: automation_id
                    .strip_prefix("Appid: ")
                    .unwrap_or(&automation_id)
                    .to_owned(),
                package_family_name: String::new(),
                count,
                count_is_lower_bound: exact_count.is_none()
                    && providers::is_discord(&automation_id),
            });
        }
        Ok(sources)
    }
}

impl Drop for TaskbarBadgeController {
    fn drop(&mut self) {
        // SAFETY: This removes the exact root and handler registration created by `start`.
        let _ = unsafe {
            self.automation
                .RemovePropertyChangedEventHandler(&self.root, &self.handler)
        };
    }
}

#[implement(IUIAutomationPropertyChangedEventHandler)]
struct BadgeChangeHandler {
    owner_thread: u32,
}

impl IUIAutomationPropertyChangedEventHandler_Impl for BadgeChangeHandler_Impl {
    fn HandlePropertyChangedEvent(
        &self,
        _sender: Ref<'_, IUIAutomationElement>,
        property_id: UIA_PROPERTY_ID,
        _new_value: &VARIANT,
    ) -> windows::core::Result<()> {
        if property_id == UIA_HelpTextPropertyId
            || property_id == UIA_AutomationIdPropertyId
        {
            post_badge_wake(self.owner_thread);
        }
        Ok(())
    }
}

pub const fn is_taskbar_badge_wake(message: u32) -> bool {
    message == BADGE_WAKE_MESSAGE
}

fn current_thread_id() -> u32 {
    // SAFETY: GetCurrentThreadId has no preconditions.
    unsafe { GetCurrentThreadId() }
}

fn post_badge_wake(owner_thread: u32) {
    // SAFETY: The UI thread remains alive for the controller lifetime and receives value data only.
    let _ = unsafe {
        PostThreadMessageW(owner_thread, BADGE_WAKE_MESSAGE, WPARAM(0), LPARAM(0))
    };
}

struct ComApartment {
    uninitialize: bool,
}

impl ComApartment {
    fn enter() -> Result<Self, WindowsError> {
        // SAFETY: The reserved pointer is null and a successful call is balanced in Drop.
        let result = unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) };
        if result.is_ok() {
            Ok(Self { uninitialize: true })
        } else if result == RPC_E_CHANGED_MODE {
            Ok(Self {
                uninitialize: false,
            })
        } else {
            Err(result.into())
        }
    }
}

impl Drop for ComApartment {
    fn drop(&mut self) {
        if self.uninitialize {
            // SAFETY: Balances this guard's successful CoInitializeEx on the same thread.
            unsafe { CoUninitialize() };
        }
    }
}
