#![allow(
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "generated by windows-core's COM implementation macro"
)]

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

use lotus_core::notification::NotificationSource;
use windows::Win32::Foundation::{E_FAIL, LPARAM, WPARAM};
use windows::Win32::System::Com::{
    CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED, CoCreateInstance, CoInitializeEx,
    CoUninitialize,
};
use windows::Win32::System::Threading::GetCurrentThreadId;
use windows::Win32::System::Variant::VARIANT;
use windows::Win32::UI::Accessibility::{
    CUIAutomation, IUIAutomation, IUIAutomationElement,
    IUIAutomationPropertyChangedEventHandler,
    IUIAutomationPropertyChangedEventHandler_Impl, TreeScope_Descendants,
    TreeScope_Subtree, UIA_AutomationIdPropertyId, UIA_HelpTextPropertyId, UIA_PROPERTY_ID,
};
use windows::Win32::UI::WindowsAndMessaging::{
    DispatchMessageW, GetMessageW, KillTimer, MSG, PM_NOREMOVE, PeekMessageW,
    PostThreadMessageW, SetTimer, TranslateMessage, WM_QUIT, WM_TIMER,
};
use windows::core::{Error as WindowsError, Ref, implement};

use super::{discovery, providers};
use crate::messages::TASKBAR_BADGE_WAKE as BADGE_WAKE_MESSAGE;
use crate::responsiveness::METRICS;

const TASKBAR_BUTTON_CLASS: &str = "Taskbar.TaskListButtonAutomationPeer";
const BADGE_SCAN_MESSAGE: u32 = BADGE_WAKE_MESSAGE + 0x80;
const BADGE_SHUTDOWN_MESSAGE: u32 = BADGE_WAKE_MESSAGE + 0x81;
const BADGE_DEBOUNCE_MS: u32 = 120;
const BADGE_MIN_SCAN_INTERVAL: Duration = Duration::from_millis(500);

pub struct TaskbarBadgeController {
    shared: Arc<SharedState>,
    worker: Option<JoinHandle<()>>,
}

struct SharedState {
    latest: Mutex<Vec<NotificationSource>>,
    ui_thread: u32,
    worker_thread: std::sync::atomic::AtomicU32,
    ui_wake_queued: AtomicBool,
    scan_queued: AtomicBool,
    running: AtomicBool,
}

struct BadgeAutomation {
    automation: IUIAutomation,
    root: IUIAutomationElement,
    handler: IUIAutomationPropertyChangedEventHandler,
    _apartment: ComApartment,
}

struct BadgeScan {
    sources: Vec<NotificationSource>,
    enumeration: Duration,
    property_reads: Duration,
    elements: usize,
    supported_elements: usize,
    provider_reads: usize,
}

impl TaskbarBadgeController {
    pub fn start() -> Result<Self, WindowsError> {
        let shared = Arc::new(SharedState {
            latest: Mutex::new(Vec::new()),
            ui_thread: current_thread_id(),
            worker_thread: std::sync::atomic::AtomicU32::new(0),
            ui_wake_queued: AtomicBool::new(false),
            scan_queued: AtomicBool::new(false),
            running: AtomicBool::new(true),
        });
        let worker_shared = Arc::clone(&shared);
        let worker = thread::Builder::new()
            .name("lotus-taskbar-badges".to_owned())
            .spawn(move || run_worker(worker_shared))
            .map_err(|error| WindowsError::new(E_FAIL, error.to_string()))?;

        Ok(Self {
            shared,
            worker: Some(worker),
        })
    }

    pub fn snapshot(&self) -> Result<Vec<NotificationSource>, WindowsError> {
        let latest =
            self.shared.latest.lock().map_err(|_| {
                WindowsError::new(E_FAIL, "Lotus badge state is unavailable")
            })?;
        self.shared.ui_wake_queued.store(false, Ordering::Release);
        Ok(latest.clone())
    }
}

impl Drop for TaskbarBadgeController {
    fn drop(&mut self) {
        self.shared.running.store(false, Ordering::Release);
        request_worker_stop(&self.shared);
        if let Some(worker) = self.worker.take()
            && worker.is_finished()
        {
            let _ = worker.join();
        }
    }
}

fn run_worker(shared: Arc<SharedState>) {
    let mut message = MSG::default();
    let _ = unsafe { PeekMessageW(&raw mut message, None, 0, 0, PM_NOREMOVE) };
    shared
        .worker_thread
        .store(current_thread_id(), Ordering::Release);
    if !shared.running.load(Ordering::Acquire) {
        shared.worker_thread.store(0, Ordering::Release);
        return;
    }
    let automation = match BadgeAutomation::start(Arc::clone(&shared)) {
        Ok(automation) => automation,
        Err(error) => {
            shared.running.store(false, Ordering::Release);
            crate::diagnostics::record_error("taskbar_badges.worker_init", &error);
            shared.worker_thread.store(0, Ordering::Release);
            return;
        }
    };
    scan_and_publish(&automation, &shared);
    if !shared.running.load(Ordering::Acquire) {
        shared.worker_thread.store(0, Ordering::Release);
        return;
    }

    worker_message_loop(&automation, &shared);
    shared.worker_thread.store(0, Ordering::Release);
    drop(shared);
}

impl BadgeAutomation {
    fn start(shared: Arc<SharedState>) -> Result<Self, WindowsError> {
        let apartment = ComApartment::enter()?;
        let automation = unsafe {
            CoCreateInstance::<_, IUIAutomation>(
                &CUIAutomation,
                None,
                CLSCTX_INPROC_SERVER,
            )?
        };
        let taskbar = discovery::taskbar_window()?;
        let host = discovery::taskbar_content_host(taskbar)?;
        let root = unsafe { automation.ElementFromHandle(host)? };
        let handler: IUIAutomationPropertyChangedEventHandler =
            BadgeChangeHandler { shared }.into();
        unsafe {
            automation.AddPropertyChangedEventHandlerNativeArray(
                &root,
                TreeScope_Subtree,
                None::<&windows::Win32::UI::Accessibility::IUIAutomationCacheRequest>,
                &handler,
                &[UIA_HelpTextPropertyId, UIA_AutomationIdPropertyId],
            )?;
        }

        Ok(Self {
            automation,
            root,
            handler,
            _apartment: apartment,
        })
    }

    fn snapshot(&self) -> Result<BadgeScan, WindowsError> {
        let enumeration_started = Instant::now();
        let condition = unsafe { self.automation.CreateTrueCondition()? };
        let elements = unsafe { self.root.FindAll(TreeScope_Descendants, &condition)? };
        let length = unsafe { elements.Length()? };
        let enumeration = enumeration_started.elapsed();
        let property_started = Instant::now();
        let mut sources = Vec::new();
        let mut supported_elements = 0;
        let mut provider_reads = 0;
        for index in 0..length {
            let element = unsafe { elements.GetElement(index)? };
            if unsafe { element.CurrentClassName()? } != TASKBAR_BUTTON_CLASS {
                continue;
            }
            let automation_id = unsafe { element.CurrentAutomationId()? }.to_string();
            let help_text = unsafe { element.CurrentHelpText()? }.to_string();
            let name = unsafe { element.CurrentName()? }.to_string();
            if !providers::is_supported_application(&automation_id, &name) {
                continue;
            }
            supported_elements += 1;
            let exact_count =
                providers::discord_badge_count(&self.automation, &automation_id);
            provider_reads += 1;
            let Some(count) =
                exact_count.or_else(|| providers::badge_count(&automation_id, &help_text))
            else {
                continue;
            };
            sources.push(NotificationSource {
                display_name: providers::taskbar_display_name(&name).to_owned(),
                app_user_model_id: automation_id
                    .strip_prefix("Appid: ")
                    .unwrap_or(&automation_id)
                    .to_owned(),
                package_family_name: String::new(),
                count,
                count_is_lower_bound: exact_count.is_none()
                    && providers::is_discord(&automation_id),
            });
        }
        Ok(BadgeScan {
            sources,
            enumeration,
            property_reads: property_started.elapsed(),
            elements: usize::try_from(length).unwrap_or(0),
            supported_elements,
            provider_reads,
        })
    }
}

impl Drop for BadgeAutomation {
    fn drop(&mut self) {
        let _ = unsafe {
            self.automation
                .RemovePropertyChangedEventHandler(&self.root, &self.handler)
        };
    }
}

fn worker_message_loop(automation: &BadgeAutomation, shared: &SharedState) {
    let mut message = MSG::default();
    let mut debounce_timer = None;
    let mut last_scan = Instant::now();
    while unsafe { GetMessageW(&raw mut message, None, 0, 0) }.as_bool() {
        match message.message {
            BADGE_SCAN_MESSAGE => restart_debounce_timer(&mut debounce_timer),
            WM_TIMER if debounce_timer == Some(message.wParam.0) => {
                cancel_timer(&mut debounce_timer);
                if let Some(remaining) =
                    BADGE_MIN_SCAN_INTERVAL.checked_sub(last_scan.elapsed())
                {
                    restart_timer(&mut debounce_timer, remaining);
                    continue;
                }
                shared.scan_queued.store(false, Ordering::Release);
                scan_and_publish(automation, shared);
                last_scan = Instant::now();
            }
            BADGE_SHUTDOWN_MESSAGE | WM_QUIT => break,
            _ => unsafe {
                let _ = TranslateMessage(&raw const message);
                DispatchMessageW(&raw const message);
            },
        }
    }
    cancel_timer(&mut debounce_timer);
}

fn scan_and_publish(automation: &BadgeAutomation, shared: &SharedState) {
    let started = Instant::now();
    let Ok(scan) = automation.snapshot() else {
        METRICS.record_badge_scan(started.elapsed());
        return;
    };
    let comparison_started = Instant::now();
    let Ok(mut latest) = shared.latest.lock() else {
        METRICS.record_badge_phases(
            scan.enumeration,
            scan.property_reads,
            comparison_started.elapsed(),
            scan.elements,
            scan.supported_elements,
            scan.provider_reads,
        );
        METRICS.record_badge_scan(started.elapsed());
        return;
    };
    let changed = *latest != scan.sources;
    if changed {
        *latest = scan.sources;
    }
    drop(latest);
    METRICS.record_badge_phases(
        scan.enumeration,
        scan.property_reads,
        comparison_started.elapsed(),
        scan.elements,
        scan.supported_elements,
        scan.provider_reads,
    );
    METRICS.record_badge_scan(started.elapsed());

    if !changed {
        return;
    }

    if shared.running.load(Ordering::Acquire)
        && !shared.ui_wake_queued.swap(true, Ordering::AcqRel)
        && unsafe {
            PostThreadMessageW(shared.ui_thread, BADGE_WAKE_MESSAGE, WPARAM(0), LPARAM(0))
        }
        .is_err()
    {
        shared.ui_wake_queued.store(false, Ordering::Release);
    }
}

fn restart_debounce_timer(timer: &mut Option<usize>) {
    restart_timer(timer, Duration::from_millis(u64::from(BADGE_DEBOUNCE_MS)));
}

fn restart_timer(timer: &mut Option<usize>, delay: Duration) {
    let milliseconds = u32::try_from(delay.as_millis().max(1)).unwrap_or(u32::MAX);
    let replacement = unsafe { SetTimer(None, 0, milliseconds, None) };
    if replacement == 0 {
        return;
    }
    cancel_timer(timer);
    *timer = Some(replacement);
}

fn cancel_timer(timer: &mut Option<usize>) {
    if let Some(timer) = timer.take() {
        let _ = unsafe { KillTimer(None, timer) };
    }
}

fn request_worker_stop(shared: &SharedState) {
    let thread_id = shared.worker_thread.load(Ordering::Acquire);
    if thread_id != 0 {
        let _ = unsafe {
            PostThreadMessageW(thread_id, BADGE_SHUTDOWN_MESSAGE, WPARAM(0), LPARAM(0))
        };
    }
}

#[implement(IUIAutomationPropertyChangedEventHandler)]
struct BadgeChangeHandler {
    shared: Arc<SharedState>,
}

impl IUIAutomationPropertyChangedEventHandler_Impl for BadgeChangeHandler_Impl {
    fn HandlePropertyChangedEvent(
        &self,
        _sender: Ref<'_, IUIAutomationElement>,
        property_id: UIA_PROPERTY_ID,
        _new_value: &VARIANT,
    ) -> windows::core::Result<()> {
        if property_id == UIA_HelpTextPropertyId
            || property_id == UIA_AutomationIdPropertyId
        {
            request_badge_scan(&self.shared);
        }
        Ok(())
    }
}

pub const fn is_taskbar_badge_wake(message: u32) -> bool {
    message == BADGE_WAKE_MESSAGE
}

fn request_badge_scan(shared: &SharedState) {
    METRICS.record_badge_event();
    if !shared.running.load(Ordering::Acquire)
        || shared.scan_queued.swap(true, Ordering::AcqRel)
    {
        METRICS.record_badge_coalesced();
        return;
    }
    let thread_id = shared.worker_thread.load(Ordering::Acquire);
    if thread_id == 0
        || unsafe {
            PostThreadMessageW(thread_id, BADGE_SCAN_MESSAGE, WPARAM(0), LPARAM(0))
        }
        .is_err()
    {
        shared.scan_queued.store(false, Ordering::Release);
    }
}

fn current_thread_id() -> u32 {
    unsafe { GetCurrentThreadId() }
}

struct ComApartment {
    uninitialize: bool,
}

impl ComApartment {
    fn enter() -> Result<Self, WindowsError> {
        let result = unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) };
        if result.is_ok() {
            Ok(Self { uninitialize: true })
        } else {
            Err(result.into())
        }
    }
}

impl Drop for ComApartment {
    fn drop(&mut self) {
        if self.uninitialize {
            unsafe { CoUninitialize() };
        }
    }
}
