[package]
name = "lotus-settings"
version = "0.8.0"
description = "Settings interface feature for Lotus"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lotus-core.workspace = true
lotus-ui.workspace = true

[lints]
workspace = true
